"""End-to-end Koza integration test for the STRING ingest.

Runs the full Koza pipeline (reader → transform → writer) against a small
200-row gzipped slice of the real human ``protein.links.v12.0`` file checked
into the repo, and asserts on the resulting JSONL output. This exercises:

  - the reader yaml (space delimiter, header on row 0, gzip detection)
  - the @koza.transform_record function (parse_string_protein_id,
    passes_combined_score, sorted_pair_key, edge construction)
  - the writer (JSONL output, KGX-compatible node/edge structure)

The unit tests in ``tests/unit/ingests/string/test_string.py`` cover the
helpers and transform in isolation. This integration test catches reader-yaml
mismatches, ID format quirks, and writer-config issues that the unit tests
can't see.
"""

import gzip
import json
from pathlib import Path

import pytest
from koza.runner import KozaRunner

from tests.util import find_project_root, get_ingest_config_yaml_path


# Directory holding both fixtures: the 200-row gzipped link file (generated by
# ``gunzip -c data/9606.protein.links.v12.0.txt.gz | head -200 | gzip > ...``)
# and a small entrez_2_string.tsv that maps 18 of the 21 above-threshold
# proteins to fake NCBIGene CURIEs. Koza resolves auxiliary files via
# ``koza.input_files_dir``, so the entrez mapping must live alongside the link
# fixture in this directory.
FIXTURE_DIR = (
    find_project_root()
    / "tests"
    / "unit"
    / "ingests"
    / "string"
    / "sample_data"
)
ENTREZ_FIXTURE = FIXTURE_DIR / "all_organisms.entrez_2_string.tsv"
# Per-taxon fixture filenames (must match string.yaml's reader configuration).
# PPI uses the ``.full.`` 16-column variant for per-channel predicate selection.
PPI_FIXTURES = [
    FIXTURE_DIR / "9606.protein.links.full.v12.0.txt.gz",
    FIXTURE_DIR / "10090.protein.links.full.v12.0.txt.gz",
    FIXTURE_DIR / "10116.protein.links.full.v12.0.txt.gz",
]
STITCH_FIXTURES = [
    FIXTURE_DIR / "9606.protein_chemical.links.v5.0.tsv.gz",
    FIXTURE_DIR / "10090.protein_chemical.links.v5.0.tsv.gz",
    FIXTURE_DIR / "10116.protein_chemical.links.v5.0.tsv.gz",
]
PPI_HEADER = [
    "protein1", "protein2",
    "neighborhood", "neighborhood_transferred",
    "fusion", "cooccurence", "homology",
    "coexpression", "coexpression_transferred",
    "experiments", "experiments_transferred",
    "database", "database_transferred",
    "textmining", "textmining_transferred",
    "combined_score",
]


@pytest.fixture(scope="module")
def koza_output(tmp_path_factory) -> Path:
    """
    Run the full Koza pipeline (both ``string_ppi`` and ``stitch_pcl`` tagged
    readers, all three taxa) once per module against the checked-in fixtures
    and return the output dir. Both tags write to the same
    ``string_nodes.jsonl`` / ``string_edges.jsonl`` files; per-tag assertions
    partition on edge primary source.
    """
    for f in [ENTREZ_FIXTURE, *PPI_FIXTURES, *STITCH_FIXTURES]:
        assert f.exists(), f"Missing fixture: {f}"
    output_dir = tmp_path_factory.mktemp("string_output")

    config_yaml_path = get_ingest_config_yaml_path("string")
    assert config_yaml_path is not None, "string.yaml not found"

    # Our fixture filenames match the yaml's `files:` declarations exactly, so
    # we don't need to override `input_files` — Koza picks them up by name from
    # the yaml and resolves them under input_files_dir. (Avoids a Koza bug in
    # the dict form of input_files combined with input_files_dir, where the
    # nested override shape is mis-applied.)
    _, runner = KozaRunner.from_config_file(
        str(config_yaml_path),
        output_dir=str(output_dir),
        input_files_dir=str(FIXTURE_DIR),
        output_format="jsonl",
    )
    runner.run()
    return output_dir


def _load_all(output_dir: Path) -> tuple[list[dict], list[dict]]:
    """Load all nodes and edges from the merged output files.

    Koza concatenates output from all tagged readers into one pair of files
    (``string_nodes.jsonl`` / ``string_edges.jsonl``), so per-tag assertions
    filter on node category / edge primary_knowledge_source.
    """
    nodes = _load_jsonl(output_dir / "string_nodes.jsonl")
    edges = _load_jsonl(output_dir / "string_edges.jsonl")
    return nodes, edges


def _ppi_partition(nodes: list[dict], edges: list[dict]) -> tuple[list[dict], list[dict]]:
    """Filter the merged output to just the STRING PPI subset."""
    ppi_edges = [
        e for e in edges
        if any(
            s["resource_id"] == "infores:string" and s["resource_role"] == "primary_knowledge_source"
            for s in e["sources"]
        )
    ]
    ppi_node_ids = {e["subject"] for e in ppi_edges} | {e["object"] for e in ppi_edges}
    ppi_nodes = [n for n in nodes if n["id"] in ppi_node_ids]
    return ppi_nodes, ppi_edges


def _stitch_partition(nodes: list[dict], edges: list[dict]) -> tuple[list[dict], list[dict]]:
    """Filter the merged output to just the STITCH PCL subset."""
    stitch_edges = [
        e for e in edges
        if any(
            s["resource_id"] == "infores:stitch" and s["resource_role"] == "primary_knowledge_source"
            for s in e["sources"]
        )
    ]
    stitch_node_ids = {e["subject"] for e in stitch_edges} | {e["object"] for e in stitch_edges}
    stitch_nodes = [n for n in nodes if n["id"] in stitch_node_ids]
    return stitch_nodes, stitch_edges


def _load_jsonl(path: Path) -> list[dict]:
    with open(path) as fh:
        return [json.loads(line) for line in fh if line.strip()]


@pytest.mark.parametrize(
    "fixture_name,expected_rows,expected_header,delimiter",
    [
        ("9606.protein.links.full.v12.0.txt.gz",     200,  PPI_HEADER, None),
        ("10090.protein.links.full.v12.0.txt.gz",    200,  PPI_HEADER, None),
        ("10116.protein.links.full.v12.0.txt.gz",    200,  PPI_HEADER, None),
        ("9606.protein_chemical.links.v5.0.tsv.gz",  5000, ["chemical", "protein", "combined_score"], "\t"),
        ("10090.protein_chemical.links.v5.0.tsv.gz", 5000, ["chemical", "protein", "combined_score"], "\t"),
        ("10116.protein_chemical.links.v5.0.tsv.gz", 5000, ["chemical", "protein", "combined_score"], "\t"),
    ],
)
def test_fixture_row_counts(fixture_name, expected_rows, expected_header, delimiter):
    """Sanity-check each fixture: row count and header."""
    path = FIXTURE_DIR / fixture_name
    with gzip.open(path, "rt") as fh:
        lines = fh.readlines()
    assert len(lines) == expected_rows, f"{fixture_name}: expected {expected_rows} rows, got {len(lines)}"
    actual_header = lines[0].strip().split(delimiter) if delimiter else lines[0].strip().split()
    assert actual_header == expected_header, f"{fixture_name}: header mismatch"


# ──── string_ppi tag: protein-protein interaction assertions ─────────────────


# All three target taxa appear in the multi-organism fixtures.
EXPECTED_TAXA = {"NCBITaxon:9606", "NCBITaxon:10090", "NCBITaxon:10116"}
# ENSEMBL protein prefixes vary by species: ENSP (human), ENSMUSP (mouse), ENSRNOP (rat).
ENSEMBL_PROTEIN_PREFIXES = ("ENSEMBL:ENSP", "ENSEMBL:ENSMUSP", "ENSEMBL:ENSRNOP")


def test_ppi_produces_nodes_and_edges(koza_output):
    nodes, edges = _ppi_partition(*_load_all(koza_output))
    # 199 rows × 3 species → roughly 30-100 above-threshold pairs per species.
    # Range is loose so the test absorbs minor STRING reissues.
    assert 30 < len(edges) < 300, f"unexpected PPI edge count: {len(edges)}"
    assert 30 < len(nodes) < 500, f"unexpected PPI node count: {len(nodes)}"


def test_ppi_node_shape(koza_output):
    nodes, _ = _ppi_partition(*_load_all(koza_output))
    seen_taxa = set()
    for node in nodes:
        assert node["id"].startswith(ENSEMBL_PROTEIN_PREFIXES), node["id"]
        assert node["category"] == ["biolink:Protein"]
        assert len(node["in_taxon"]) == 1 and node["in_taxon"][0] in EXPECTED_TAXA, node["in_taxon"]
        seen_taxa.add(node["in_taxon"][0])
    # All three taxa should appear at least once in the output.
    assert seen_taxa == EXPECTED_TAXA, f"missing taxa: {EXPECTED_TAXA - seen_taxa}"


def test_ppi_equivalent_identifiers_populated_from_mapping_fixture(koza_output):
    """The fixture mapping covers 18 of 21 distinct proteins above threshold.
    Verify most PPI nodes carry NCBIGene equivalents (proves the on_data_begin
    hook loaded the mapping end-to-end)."""
    nodes, _ = _ppi_partition(*_load_all(koza_output))
    with_equivs = [n for n in nodes if n.get("equivalent_identifiers")]
    assert len(with_equivs) > 0, "no nodes got equivalent_identifiers — mapping load failed?"
    for node in with_equivs:
        for eq in node["equivalent_identifiers"]:
            assert eq.startswith("NCBIGene:"), eq


# Per-channel predicates emitted by string_ppi (matches CHANNEL_PREDICATES +
# FALLBACK_PREDICATE in string.py).
PPI_PREDICATES = {
    "biolink:physically_interacts_with",  # experiments channel + fallback
    "biolink:coexpressed_with",           # coexpression channel
    "biolink:interacts_with",             # textmining channel
    "biolink:gene_fusion_with",           # fusion channel
    "biolink:genetic_neighborhood_of",    # neighborhood channel
    "biolink:genetically_interacts_with", # cooccurence channel
}
# Edge classes that may appear in PPI output. PairwiseMolecularInteraction
# covers most predicates; GeneToGeneCoexpressionAssociation is the canonical
# class for coexpressed_with.
PPI_CATEGORIES = {
    "biolink:PairwiseMolecularInteraction",
    "biolink:GeneToGeneCoexpressionAssociation",
}


def test_ppi_edge_shape(koza_output):
    _, edges = _ppi_partition(*_load_all(koza_output))
    for edge in edges:
        assert edge["category"][0] in PPI_CATEGORIES, edge["category"]
        assert edge["predicate"] in PPI_PREDICATES, edge["predicate"]
        assert edge["subject"].startswith(ENSEMBL_PROTEIN_PREFIXES)
        assert edge["object"].startswith(ENSEMBL_PROTEIN_PREFIXES)
        assert edge["knowledge_level"] == "not_provided"
        assert edge["agent_type"] == "not_provided"
        # MI:0915 only attaches to physically_interacts_with edges; omitted for others.
        if edge["predicate"] == "biolink:physically_interacts_with":
            assert edge.get("has_attribute") == ["MI:0915"]
        else:
            assert not edge.get("has_attribute")


def test_ppi_emits_multiple_predicates(koza_output):
    """At least the fallback predicate is always emitted; high-confidence
    channels in fixture data should yield additional predicate variety."""
    _, edges = _ppi_partition(*_load_all(koza_output))
    predicates_seen = {e["predicate"] for e in edges}
    assert "biolink:physically_interacts_with" in predicates_seen, \
        "fallback predicate should always appear for above-threshold rows"
    # Mouse fixture has ~15 high-conf rows; rat ~3; human ~2 — expect at least
    # one non-fallback predicate to fire across the combined output.
    non_fallback = predicates_seen - {"biolink:physically_interacts_with"}
    assert len(non_fallback) >= 1, \
        f"expected at least one non-fallback predicate, got: {predicates_seen}"


def test_ppi_no_duplicate_edges_by_unordered_pair(koza_output):
    """Symmetric duplicate rows in STRING should be collapsed to one edge."""
    _, edges = _ppi_partition(*_load_all(koza_output))
    pair_keys = {tuple(sorted([e["subject"], e["object"]])) for e in edges}
    assert len(pair_keys) == len(edges), "symmetric duplicates leaked into PPI output"


# ──── stitch_pcl tag: protein-chemical interaction assertions ────────────────


def test_stitch_produces_nodes_and_edges(koza_output):
    nodes, edges = _stitch_partition(*_load_all(koza_output))
    # 4,999 data rows × 3 species → roughly 25-50 above-threshold pairs per species.
    assert 30 < len(edges) < 200, f"unexpected STITCH edge count: {len(edges)}"
    assert 30 < len(nodes) < 400, f"unexpected STITCH node count: {len(nodes)}"


def test_stitch_emits_chemical_and_protein_nodes(koza_output):
    nodes, _ = _stitch_partition(*_load_all(koza_output))
    chemicals = [n for n in nodes if n["category"] == ["biolink:ChemicalEntity"]]
    proteins = [n for n in nodes if n["category"] == ["biolink:Protein"]]
    assert len(chemicals) > 0, "no chemical nodes emitted"
    assert len(proteins) > 0, "no protein nodes emitted"
    assert len(chemicals) + len(proteins) == len(nodes), "unexpected category in STITCH output"

    for chem in chemicals:
        assert chem["id"].startswith("PUBCHEM.COMPOUND:"), chem["id"]
    seen_taxa = set()
    for prot in proteins:
        assert prot["id"].startswith(ENSEMBL_PROTEIN_PREFIXES), prot["id"]
        assert len(prot["in_taxon"]) == 1 and prot["in_taxon"][0] in EXPECTED_TAXA
        seen_taxa.add(prot["in_taxon"][0])
    assert seen_taxa == EXPECTED_TAXA, f"STITCH missing taxa: {EXPECTED_TAXA - seen_taxa}"


def test_stitch_edge_shape(koza_output):
    _, edges = _stitch_partition(*_load_all(koza_output))
    for edge in edges:
        assert edge["predicate"] == "biolink:interacts_with"
        assert edge["subject"].startswith("PUBCHEM.COMPOUND:")
        assert edge["object"].startswith(ENSEMBL_PROTEIN_PREFIXES)
        assert edge["knowledge_level"] == "not_provided"
        assert edge["agent_type"] == "not_provided"
        assert edge["has_attribute"] == ["MI:0190"]


# ──── merged-output assertions (both tags) ───────────────────────────────────


def test_merged_output_partition_covers_all(koza_output):
    """Every emitted edge belongs to exactly one of the two source partitions."""
    nodes, edges = _load_all(koza_output)
    ppi_nodes, ppi_edges = _ppi_partition(nodes, edges)
    stitch_nodes, stitch_edges = _stitch_partition(nodes, edges)
    assert len(ppi_edges) + len(stitch_edges) == len(edges), \
        "an edge falls outside both partitions"


def test_no_duplicate_nodes_in_merged_output(koza_output):
    """Each node id appears at most once across the combined output."""
    nodes, _ = _load_all(koza_output)
    ids = [n["id"] for n in nodes]
    assert len(ids) == len(set(ids)), "duplicate node IDs in merged output"
