"""End-to-end Koza integration test for the STRING ingest.

Runs the full Koza pipeline (reader → transform → writer) against a small
200-row gzipped slice of the real human ``protein.links.v12.0`` file checked
into the repo, and asserts on the resulting JSONL output. This exercises:

  - the reader yaml (space delimiter, header on row 0, gzip detection)
  - the @koza.transform_record function (parse_string_protein_id,
    passes_combined_score, sorted_pair_key, edge construction)
  - the writer (JSONL output, KGX-compatible node/edge structure)

The unit tests in ``tests/unit/ingests/string/test_string.py`` cover the
helpers and transform in isolation. This integration test catches reader-yaml
mismatches, ID format quirks, and writer-config issues that the unit tests
can't see.
"""

import gzip
import json
from pathlib import Path

import pytest
from koza.runner import KozaRunner

from tests.util import find_project_root, get_ingest_config_yaml_path


# 200-row slice of the real STRING human file, generated by:
#   gunzip -c data/9606.protein.links.v12.0.txt.gz | head -200 | gzip > <this fixture>
FIXTURE_PATH = (
    find_project_root()
    / "tests"
    / "unit"
    / "ingests"
    / "string"
    / "sample_data"
    / "9606.protein.links.v12.0.txt.gz"
)


@pytest.fixture(scope="module")
def koza_output(tmp_path_factory) -> Path:
    """Run koza transform once per module against the fixture and return the output dir."""
    assert FIXTURE_PATH.exists(), f"Missing fixture: {FIXTURE_PATH}"
    output_dir = tmp_path_factory.mktemp("string_output")

    config_yaml_path = get_ingest_config_yaml_path("string")
    assert config_yaml_path is not None, "string.yaml not found"

    _, runner = KozaRunner.from_config_file(
        str(config_yaml_path),
        output_dir=str(output_dir),
        input_files=[str(FIXTURE_PATH)],
        output_format="jsonl",
    )
    runner.run()
    return output_dir


def _load_jsonl(path: Path) -> list[dict]:
    with open(path) as fh:
        return [json.loads(line) for line in fh if line.strip()]


def test_fixture_row_count():
    """Sanity-check the fixture itself: 200 rows including the header."""
    with gzip.open(FIXTURE_PATH, "rt") as fh:
        lines = fh.readlines()
    assert len(lines) == 200
    assert lines[0].strip().split() == ["protein1", "protein2", "combined_score"]


def test_transform_produces_nodes_and_edges(koza_output):
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    edges = _load_jsonl(koza_output / "string_edges.jsonl")
    # 199 data rows → some pass the >500 cutoff, some don't. The exact pass
    # count depends on the real data; we assert plausibility rather than exact
    # equality so this test doesn't get brittle if STRING reissues v12.0.
    assert 5 < len(edges) < 100, f"unexpected edge count: {len(edges)}"
    assert 5 < len(nodes) < 200, f"unexpected node count: {len(nodes)}"


def test_node_shape(koza_output):
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    for node in nodes:
        assert node["id"].startswith("ENSEMBL:ENSP"), node["id"]
        assert node["category"] == ["biolink:Protein"]
        assert node["in_taxon"] == ["NCBITaxon:9606"]


def test_edge_shape(koza_output):
    edges = _load_jsonl(koza_output / "string_edges.jsonl")
    for edge in edges:
        assert edge["category"] == ["biolink:PairwiseMolecularInteraction"]
        assert edge["predicate"] == "biolink:physically_interacts_with"
        assert edge["subject"].startswith("ENSEMBL:ENSP")
        assert edge["object"].startswith("ENSEMBL:ENSP")
        assert edge["knowledge_level"] == "knowledge_assertion"
        assert edge["agent_type"] == "not_provided"
        sources = edge["sources"]
        primary = next(s for s in sources if s["resource_role"] == "primary_knowledge_source")
        assert primary["resource_id"] == "infores:string"


def test_no_duplicate_nodes(koza_output):
    """Each protein appears as a node at most once across the output."""
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    ids = [n["id"] for n in nodes]
    assert len(ids) == len(set(ids)), "duplicate node IDs in output"


def test_no_duplicate_edges_by_unordered_pair(koza_output):
    """Symmetric duplicate rows in STRING should be collapsed to one edge."""
    edges = _load_jsonl(koza_output / "string_edges.jsonl")
    pair_keys = {tuple(sorted([e["subject"], e["object"]])) for e in edges}
    assert len(pair_keys) == len(edges), "symmetric duplicates leaked into output"
