"""End-to-end Koza integration test for the STRING ingest.

Runs the full Koza pipeline (reader → transform → writer) against a small
200-row gzipped slice of the real human ``protein.links.v12.0`` file checked
into the repo, and asserts on the resulting JSONL output. This exercises:

  - the reader yaml (space delimiter, header on row 0, gzip detection)
  - the @koza.transform_record function (parse_string_protein_id,
    passes_combined_score, sorted_pair_key, edge construction)
  - the writer (JSONL output, KGX-compatible node/edge structure)

The unit tests in ``tests/unit/ingests/string/test_string.py`` cover the
helpers and transform in isolation. This integration test catches reader-yaml
mismatches, ID format quirks, and writer-config issues that the unit tests
can't see.
"""

import gzip
import json
from pathlib import Path

import pytest
from koza.runner import KozaRunner

from tests.util import find_project_root, get_ingest_config_yaml_path


# Directory holding both fixtures: the 200-row gzipped link file (generated by
# ``gunzip -c data/9606.protein.links.v12.0.txt.gz | head -200 | gzip > ...``)
# and a small entrez_2_string.tsv that maps 18 of the 21 above-threshold
# proteins to fake NCBIGene CURIEs. Koza resolves auxiliary files via
# ``koza.input_files_dir``, so the entrez mapping must live alongside the link
# fixture in this directory.
FIXTURE_DIR = (
    find_project_root()
    / "tests"
    / "unit"
    / "ingests"
    / "string"
    / "sample_data"
)
LINK_FIXTURE = FIXTURE_DIR / "9606.protein.links.v12.0.txt.gz"
ENTREZ_FIXTURE = FIXTURE_DIR / "all_organisms.entrez_2_string.tsv"


@pytest.fixture(scope="module")
def koza_output(tmp_path_factory) -> Path:
    """Run koza transform once per module against the fixture and return the output dir."""
    assert LINK_FIXTURE.exists(), f"Missing link fixture: {LINK_FIXTURE}"
    assert ENTREZ_FIXTURE.exists(), f"Missing entrez mapping fixture: {ENTREZ_FIXTURE}"
    output_dir = tmp_path_factory.mktemp("string_output")

    config_yaml_path = get_ingest_config_yaml_path("string")
    assert config_yaml_path is not None, "string.yaml not found"

    _, runner = KozaRunner.from_config_file(
        str(config_yaml_path),
        output_dir=str(output_dir),
        input_files=[LINK_FIXTURE.name],
        input_files_dir=str(FIXTURE_DIR),
        output_format="jsonl",
    )
    runner.run()
    return output_dir


def _load_jsonl(path: Path) -> list[dict]:
    with open(path) as fh:
        return [json.loads(line) for line in fh if line.strip()]


def test_fixture_row_count():
    """Sanity-check the fixture itself: 200 rows including the header."""
    with gzip.open(LINK_FIXTURE, "rt") as fh:
        lines = fh.readlines()
    assert len(lines) == 200
    assert lines[0].strip().split() == ["protein1", "protein2", "combined_score"]


def test_transform_produces_nodes_and_edges(koza_output):
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    edges = _load_jsonl(koza_output / "string_edges.jsonl")
    # 199 data rows → some pass the >500 cutoff, some don't. The exact pass
    # count depends on the real data; we assert plausibility rather than exact
    # equality so this test doesn't get brittle if STRING reissues v12.0.
    assert 5 < len(edges) < 100, f"unexpected edge count: {len(edges)}"
    assert 5 < len(nodes) < 200, f"unexpected node count: {len(nodes)}"


def test_node_shape(koza_output):
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    for node in nodes:
        assert node["id"].startswith("ENSEMBL:ENSP"), node["id"]
        assert node["category"] == ["biolink:Protein"]
        assert node["in_taxon"] == ["NCBITaxon:9606"]


def test_equivalent_identifiers_populated_from_mapping_fixture(koza_output):
    """The fixture mapping covers 18 of 21 distinct proteins above threshold.
    Verify most nodes carry NCBIGene equivalents, and at least one doesn't
    (proving both code paths execute end-to-end)."""
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    with_equivs = [n for n in nodes if n.get("equivalent_identifiers")]
    without_equivs = [n for n in nodes if not n.get("equivalent_identifiers")]
    assert len(with_equivs) > 0, "no nodes got equivalent_identifiers — mapping load failed?"
    # The fixture maps 18 of the 21 distinct above-threshold proteins; we expect
    # most nodes to be in with_equivs. Not all nodes appear in every edge, so
    # the exact count depends on which proteins participate in passing edges.
    for node in with_equivs:
        for eq in node["equivalent_identifiers"]:
            assert eq.startswith("NCBIGene:"), eq


def test_edge_shape(koza_output):
    edges = _load_jsonl(koza_output / "string_edges.jsonl")
    for edge in edges:
        assert edge["category"] == ["biolink:PairwiseMolecularInteraction"]
        assert edge["predicate"] == "biolink:physically_interacts_with"
        assert edge["subject"].startswith("ENSEMBL:ENSP")
        assert edge["object"].startswith("ENSEMBL:ENSP")
        assert edge["knowledge_level"] == "not_provided"
        assert edge["agent_type"] == "not_provided"
        # PSI-MI interaction-type CURIE attached via has_attribute.
        assert edge["has_attribute"] == ["MI:0915"]
        sources = edge["sources"]
        primary = next(s for s in sources if s["resource_role"] == "primary_knowledge_source")
        assert primary["resource_id"] == "infores:string"


def test_no_duplicate_nodes(koza_output):
    """Each protein appears as a node at most once across the output."""
    nodes = _load_jsonl(koza_output / "string_nodes.jsonl")
    ids = [n["id"] for n in nodes]
    assert len(ids) == len(set(ids)), "duplicate node IDs in output"


def test_no_duplicate_edges_by_unordered_pair(koza_output):
    """Symmetric duplicate rows in STRING should be collapsed to one edge."""
    edges = _load_jsonl(koza_output / "string_edges.jsonl")
    pair_keys = {tuple(sorted([e["subject"], e["object"]])) for e in edges}
    assert len(pair_keys) == len(edges), "symmetric duplicates leaked into output"
